{
 "title": "SP4 Sinter Plant — Process ESP & DDESP",
 "tags": [
  "sp4",
  "esp",
  "ddesp",
  "gas-cleaning",
  "litmus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "marcuscalidus-svg-panel",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 0 },
   "format": "short",
   "targets": [
    {
     "alias": "TR_6_SECONDARY_VOLTAGE_kV_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_6_SECONDARY_VOLTAGE_kV_' AND $timeFilter"
    },
    {
     "alias": "TR_6_SECONDARY_CURRENT_mA_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_6_SECONDARY_CURRENT_mA_' AND $timeFilter"
    },
    {
     "alias": "TR_7_SECONDARY_VOLTAGE_kV_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_7_SECONDARY_VOLTAGE_kV_' AND $timeFilter"
    },
    {
     "alias": "TR_7_SECONDARY_CURRENT_mA_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_7_SECONDARY_CURRENT_mA_' AND $timeFilter"
    },
    {
     "alias": "TR_8_SECONDARY_VOLTAGE_kV_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_8_SECONDARY_VOLTAGE_kV_' AND $timeFilter"
    },
    {
     "alias": "TR_8_SECONDARY_CURRENT_mA_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_8_SECONDARY_CURRENT_mA_' AND $timeFilter"
    },
    {
     "alias": "TR_9_SECONDARY_VOLTAGE_kV_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_9_SECONDARY_VOLTAGE_kV_' AND $timeFilter"
    },
    {
     "alias": "TR_9_SECONDARY_CURRENT_mA_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_9_SECONDARY_CURRENT_mA_' AND $timeFilter"
    },
    {
     "alias": "TR_10_SECONDARY_VOLTAGE_kV_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_10_SECONDARY_VOLTAGE_kV_' AND $timeFilter"
    },
    {
     "alias": "TR_10_SECONDARY_CURRENT_mA_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_10_SECONDARY_CURRENT_mA_' AND $timeFilter"
    },
    {
     "alias": "TR_1_SECONDARY_VOLTAGE_kV_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_1_SECONDARY_VOLTAGE_kV_' AND $timeFilter"
    },
    {
     "alias": "TR_1_SECONDARY_CURRENT_mA_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_1_SECONDARY_CURRENT_mA_' AND $timeFilter"
    },
    {
     "alias": "TR_2_SECONDARY_VOLTAGE_kV_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_2_SECONDARY_VOLTAGE_kV_' AND $timeFilter"
    },
    {
     "alias": "TR_2_SECONDARY_CURRENT_mA_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_2_SECONDARY_CURRENT_mA_' AND $timeFilter"
    },
    {
     "alias": "TR_3_SECONDARY_VOLTAGE_kV_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_3_SECONDARY_VOLTAGE_kV_' AND $timeFilter"
    },
    {
     "alias": "TR_3_SECONDARY_CURRENT_mA_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_3_SECONDARY_CURRENT_mA_' AND $timeFilter"
    },
    {
     "alias": "TR_4_SECONDARY_VOLTAGE_kV_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_4_SECONDARY_VOLTAGE_kV_' AND $timeFilter"
    },
    {
     "alias": "TR_4_SECONDARY_CURRENT_mA_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_4_SECONDARY_CURRENT_mA_' AND $timeFilter"
    },
    {
     "alias": "TR_5_SECONDARY_VOLTAGE_kV_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_5_SECONDARY_VOLTAGE_kV_' AND $timeFilter"
    },
    {
     "alias": "TR_5_SECONDARY_CURRENT_mA_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_5_SECONDARY_CURRENT_mA_' AND $timeFilter"
    },
    {
     "alias": "TR_11_SECONDARY_VOLTAGE_kV_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_11_SECONDARY_VOLTAGE_kV_' AND $timeFilter"
    },
    {
     "alias": "TR_11_SECONDARY_CURRENT_mA_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_11_SECONDARY_CURRENT_mA_' AND $timeFilter"
    },
    {
     "alias": "TR_12_SECONDARY_VOLTAGE_kV_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_12_SECONDARY_VOLTAGE_kV_' AND $timeFilter"
    },
    {
     "alias": "TR_12_SECONDARY_CURRENT_mA_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_12_SECONDARY_CURRENT_mA_' AND $timeFilter"
    },
    {
     "alias": "TR_13_SECONDARY_VOLTAGE_kV_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_13_SECONDARY_VOLTAGE_kV_' AND $timeFilter"
    },
    {
     "alias": "TR_13_SECONDARY_CURRENT_mA_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_13_SECONDARY_CURRENT_mA_' AND $timeFilter"
    },
    {
     "alias": "TR_14_SECONDARY_VOLTAGE_kV_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_14_SECONDARY_VOLTAGE_kV_' AND $timeFilter"
    },
    {
     "alias": "TR_14_SECONDARY_CURRENT_mA_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_14_SECONDARY_CURRENT_mA_' AND $timeFilter"
    },
    {
     "alias": "TR_15_SECONDARY_VOLTAGE_kV_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_15_SECONDARY_VOLTAGE_kV_' AND $timeFilter"
    },
    {
     "alias": "TR_15_SECONDARY_CURRENT_mA_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_15_SECONDARY_CURRENT_mA_' AND $timeFilter"
    },
    {
     "alias": "TR_201_SECONDARY_VOLTAGE_kV_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_201_SECONDARY_VOLTAGE_kV_' AND $timeFilter"
    },
    {
     "alias": "TR_201_SECONDARY_CURRENT_mA_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_201_SECONDARY_CURRENT_mA_' AND $timeFilter"
    },
    {
     "alias": "TR_202_SECONDARY_VOLTAGE_kV_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_202_SECONDARY_VOLTAGE_kV_' AND $timeFilter"
    },
    {
     "alias": "TR_202_SECONDARY_CURRENT_mA_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_202_SECONDARY_CURRENT_mA_' AND $timeFilter"
    },
    {
     "alias": "TR_203_SECONDARY_VOLTAGE_kV_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_203_SECONDARY_VOLTAGE_kV_' AND $timeFilter"
    },
    {
     "alias": "TR_203_SECONDARY_CURRENT_mA_",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_203_SECONDARY_CURRENT_mA_' AND $timeFilter"
    },
    {
     "alias": "SINTER_M_C_CURRENT",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'SINTER_M_C_CURRENT' AND $timeFilter"
    },
    {
     "alias": "STACK_PM",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'STACK_PM' AND $timeFilter"
    },
    {
     "alias": "WGF_SPEED_ACTUAL",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_SPEED_ACTUAL' AND $timeFilter"
    },
    {
     "alias": "CC_1_CURRENT",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'CC_1_CURRENT' AND $timeFilter"
    },
    {
     "alias": "CC_2_CURRENT",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'CC_2_CURRENT' AND $timeFilter"
    },
    {
     "alias": "CC_3_CURRENT",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'CC_3_CURRENT' AND $timeFilter"
    },
    {
     "alias": "CC_4_CURRENT",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'CC_4_CURRENT' AND $timeFilter"
    },
    {
     "alias": "CC_5_CURRENT",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'CC_5_CURRENT' AND $timeFilter"
    },
    {
     "alias": "CV_6_CURRENT",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'CV_6_CURRENT' AND $timeFilter"
    },
    {
     "alias": "CV_7_CURRENT",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'CV_7_CURRENT' AND $timeFilter"
    },
    {
     "alias": "F1004M01_CURRENT",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'F1004M01_CURRENT' AND $timeFilter"
    },
    {
     "alias": "F1005M01_CURRENT",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'F1005M01_CURRENT' AND $timeFilter"
    },
    {
     "alias": "F1006M01_CURRENT",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'F1006M01_CURRENT' AND $timeFilter"
    },
    {
     "alias": "F1008M01_CURRENT",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'F1008M01_CURRENT' AND $timeFilter"
    },
    {
     "alias": "F1015M01_CURRENT",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'F1015M01_CURRENT' AND $timeFilter"
    },
    {
     "alias": "F1016M01_CURRENT",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'F1016M01_CURRENT' AND $timeFilter"
    },
    {
     "alias": "F1017M01_CURRENT",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'F1017M01_CURRENT' AND $timeFilter"
    },
    {
     "alias": "F2008M01_CURRENT",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'F2008M01_CURRENT' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Stack PM Emission (last 30m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "STACK_PM",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'STACK_PM' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  },
  {
   "title": "Sinter M/C Current (last 30m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "SINTER_M_C_CURRENT",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'SINTER_M_C_CURRENT' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  },
  {
   "title": "ESP Pass C TR Currents (TR11-15)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "TR_11_SECONDARY_CURRENT_mA_",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_11_SECONDARY_CURRENT_mA_' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    },
    {
     "alias": "TR_12_SECONDARY_CURRENT_mA_",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_12_SECONDARY_CURRENT_mA_' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    },
    {
     "alias": "TR_13_SECONDARY_CURRENT_mA_",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_13_SECONDARY_CURRENT_mA_' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    },
    {
     "alias": "TR_14_SECONDARY_CURRENT_mA_",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_14_SECONDARY_CURRENT_mA_' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    },
    {
     "alias": "TR_15_SECONDARY_CURRENT_mA_",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_15_SECONDARY_CURRENT_mA_' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  },
  {
   "title": "DDESP TR Currents (TR201-203)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "TR_201_SECONDARY_CURRENT_mA_",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_201_SECONDARY_CURRENT_mA_' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    },
    {
     "alias": "TR_202_SECONDARY_CURRENT_mA_",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_202_SECONDARY_CURRENT_mA_' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    },
    {
     "alias": "TR_203_SECONDARY_CURRENT_mA_",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'TR_203_SECONDARY_CURRENT_mA_' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  }
 ]
}