{
 "title": "SP4 Sinter Plant — WGF Machine Health",
 "tags": [
  "sp4",
  "wgf",
  "machine-health",
  "litmus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "type": "marcuscalidus-svg-panel",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 0 },
   "format": "short",
   "targets": [
    {
     "alias": "WGF_SPEED",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_SPEED' AND $timeFilter"
    },
    {
     "alias": "WGF_DC_CURRENT",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_DC_CURRENT' AND $timeFilter"
    },
    {
     "alias": "WGF_EXCITATION_CURRENT",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_EXCITATION_CURRENT' AND $timeFilter"
    },
    {
     "alias": "WGF_MOTOR_U1_WINDING_TEMPERATURE",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_U1_WINDING_TEMPERATURE' AND $timeFilter"
    },
    {
     "alias": "WGF_MOTOR_V1_WINDING_TEMPERATURE",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_V1_WINDING_TEMPERATURE' AND $timeFilter"
    },
    {
     "alias": "WGF_MOTOR_W1_WINDING_TEMPERATURE",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_W1_WINDING_TEMPERATURE' AND $timeFilter"
    },
    {
     "alias": "WGF_MOTOR_U2_WINDING_TEMPERATURE",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_U2_WINDING_TEMPERATURE' AND $timeFilter"
    },
    {
     "alias": "WGF_MOTOR_V2_WINDING_TEMPERATURE",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_V2_WINDING_TEMPERATURE' AND $timeFilter"
    },
    {
     "alias": "WGF_MOTOR_W2_WINDING_TEMPERATURE",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_W2_WINDING_TEMPERATURE' AND $timeFilter"
    },
    {
     "alias": "WGF_MOTOR_DE_BEARING_TEMPERATURE",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_DE_BEARING_TEMPERATURE' AND $timeFilter"
    },
    {
     "alias": "WGF_MOTOR_NDE_BEARING_TEMPERATURE",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_NDE_BEARING_TEMPERATURE' AND $timeFilter"
    },
    {
     "alias": "WGF_FAN_DE_X_VIBRATION",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_DE_X_VIBRATION' AND $timeFilter"
    },
    {
     "alias": "WGF_FAN_DE_Y_VIBRATION",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_DE_Y_VIBRATION' AND $timeFilter"
    },
    {
     "alias": "WGF_FAN_DE_AXIAL_VIBRATION",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_DE_AXIAL_VIBRATION' AND $timeFilter"
    },
    {
     "alias": "WGF_FAN_NDE_X_VIBRATION",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_NDE_X_VIBRATION' AND $timeFilter"
    },
    {
     "alias": "WGF_FAN_NDE_Y_VIBRATION",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_NDE_Y_VIBRATION' AND $timeFilter"
    },
    {
     "alias": "WGF_FAN_NDE_AXIAL_VIBRATION",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_NDE_AXIAL_VIBRATION' AND $timeFilter"
    },
    {
     "alias": "WGF_MOTOR_DE_AXIAL_VIBRATION",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_DE_AXIAL_VIBRATION' AND $timeFilter"
    },
    {
     "alias": "WGF_MOTOR_NDE_AXIAL_VIBRATION",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_NDE_AXIAL_VIBRATION' AND $timeFilter"
    },
    {
     "alias": "WGF_FAN_DE_LUBRICATIONOIL_FLOW",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_DE_LUBRICATIONOIL_FLOW' AND $timeFilter"
    },
    {
     "alias": "WGF_FAN_DE_LUBRICATIONOIL_PRESSURE",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_DE_LUBRICATIONOIL_PRESSURE' AND $timeFilter"
    },
    {
     "alias": "WGF_FAN_DE_LUBRICATIONOIL_TEMPERATURE",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_DE_LUBRICATIONOIL_TEMPERATURE' AND $timeFilter"
    },
    {
     "alias": "WGF_FAN_NDE_LUBRICATIONOIL_FLOW",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_NDE_LUBRICATIONOIL_FLOW' AND $timeFilter"
    },
    {
     "alias": "WGF_FAN_NDE_LUBRICATIONOIL_PRESSURE",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_NDE_LUBRICATIONOIL_PRESSURE' AND $timeFilter"
    },
    {
     "alias": "WGF_FAN_NDE_LUBRICATIONOIL_TEMPERATURE",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_NDE_LUBRICATIONOIL_TEMPERATURE' AND $timeFilter"
    },
    {
     "alias": "WGF_MOTOR_DE_LUBRICATIONOIL_FLOW",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_DE_LUBRICATIONOIL_FLOW' AND $timeFilter"
    },
    {
     "alias": "WGF_MOTOR_DE_LUBRICATIONOIL_PRESSURE",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_DE_LUBRICATIONOIL_PRESSURE' AND $timeFilter"
    },
    {
     "alias": "WGF_MOTOR_DE_LUBRICATIONOIL_TEMPERATURE",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_DE_LUBRICATIONOIL_TEMPERATURE' AND $timeFilter"
    },
    {
     "alias": "WGF_MOTOR_NDE_LUBRICATIONOIL_FLOW",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_NDE_LUBRICATIONOIL_FLOW' AND $timeFilter"
    },
    {
     "alias": "WGF_MOTOR_NDE_LUBRICATIONOIL_PRESSURE",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_NDE_LUBRICATIONOIL_PRESSURE' AND $timeFilter"
    },
    {
     "alias": "WGF_MOTOR_NDE_LUBRICATIONOIL_TEMPERATURE",
     "query": "SELECT last(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_NDE_LUBRICATIONOIL_TEMPERATURE' AND $timeFilter"
    }
   ]
  },
  {
   "title": "Fan DE Vibrations (X/Y/Axial)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "WGF_FAN_DE_X_VIBRATION",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_DE_X_VIBRATION' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    },
    {
     "alias": "WGF_FAN_DE_Y_VIBRATION",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_DE_Y_VIBRATION' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    },
    {
     "alias": "WGF_FAN_DE_AXIAL_VIBRATION",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_DE_AXIAL_VIBRATION' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  },
  {
   "title": "Fan NDE Vibrations (X/Y/Axial)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "WGF_FAN_NDE_X_VIBRATION",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_NDE_X_VIBRATION' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    },
    {
     "alias": "WGF_FAN_NDE_Y_VIBRATION",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_NDE_Y_VIBRATION' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    },
    {
     "alias": "WGF_FAN_NDE_AXIAL_VIBRATION",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_NDE_AXIAL_VIBRATION' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  },
  {
   "title": "Motor Bearing Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "WGF_MOTOR_DE_BEARING_TEMPERATURE",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_DE_BEARING_TEMPERATURE' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    },
    {
     "alias": "WGF_MOTOR_NDE_BEARING_TEMPERATURE",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_NDE_BEARING_TEMPERATURE' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  },
  {
   "title": "Lube Oil Pressures (4 circuits)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "WGF_FAN_DE_LUBRICATIONOIL_PRESSURE",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_DE_LUBRICATIONOIL_PRESSURE' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    },
    {
     "alias": "WGF_FAN_NDE_LUBRICATIONOIL_PRESSURE",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_FAN_NDE_LUBRICATIONOIL_PRESSURE' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    },
    {
     "alias": "WGF_MOTOR_DE_LUBRICATIONOIL_PRESSURE",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_DE_LUBRICATIONOIL_PRESSURE' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    },
    {
     "alias": "WGF_MOTOR_NDE_LUBRICATIONOIL_PRESSURE",
     "query": "SELECT mean(\"value\") FROM \"SP4Iba.94F1A3D6-7319-4C42-8744-CFE06FD3D360\" WHERE \"tag\" = 'WGF_MOTOR_NDE_LUBRICATIONOIL_PRESSURE' AND $timeFilter GROUP BY time($__interval) fill(linear)"
    }
   ]
  }
 ]
}